version: "3"
services:
  nginx:
    image: chikara/nginx
    ports:
      - 80:80
    networks:
      - webnet
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  node:
    image: chikara/egg-example
    networks:
      - webnet
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  mysql:
    image: mysql:5.7
    environment:
    - MYSQL_ROOT_PASSWORD=123456
    networks:
      - webnet
    volumes:
      - mysql:/var/lib/mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
networks:
  webnet:
volumes:
  mysql: